import { useState, useEffect, useCallback } from 'react';
import { Edit2, Check, X, Loader2, RefreshCw } from 'lucide-react';
import { magicCodeApi } from '../utils/api';

export default function MagicCodeInput({ 
  value, 
  onChange, 
  startupId = null, 
  disabled = false,
  error: externalError = null 
}) {
  const [isCustomMode, setIsCustomMode] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [customCode, setCustomCode] = useState('');
  const [isValidating, setIsValidating] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [validationError, setValidationError] = useState(null);
  const [isValid, setIsValid] = useState(true);

  // Fetch auto-generated code on mount (only for new startups)
  useEffect(() => {
    if (!startupId && !value) {
      generateNewCode();
    } else if (value) {
      setAutoGeneratedCode(value);
      setCustomCode(value);
    }
  }, [startupId]);

  const generateNewCode = async () => {
    setIsGenerating(true);
    try {
      const result = await magicCodeApi.generate();
      setAutoGeneratedCode(result.code);
      if (!isCustomMode) {
        onChange(result.code);
      }
    } catch (err) {
      console.error('Failed to generate magic code:', err);
      // Fallback to timestamp-based code
      const fallback = `MAGIC-${String(Date.now()).slice(-4)}`;
      setAutoGeneratedCode(fallback);
      if (!isCustomMode) {
        onChange(fallback);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  // Debounced validation
  const validateCode = useCallback(async (code) => {
    if (!code || code.length < 10) {
      setValidationError(null);
      setIsValid(false);
      return;
    }

    // Check format first
    const formatValid = /^MAGIC-\d{4}$/.test(code);
    if (!formatValid) {
      setValidationError('Format must be MAGIC-XXXX (4 digits)');
      setIsValid(false);
      return;
    }

    setIsValidating(true);
    try {
      const result = await magicCodeApi.validate(code, startupId);
      setIsValid(result.isValid && result.isAvailable);
      setValidationError(result.error);
    } catch (err) {
      console.error('Validation error:', err);
      setValidationError('Failed to validate code');
      setIsValid(false);
    } finally {
      setIsValidating(false);
    }
  }, [startupId]);

  // Validate on custom code change with debounce
  useEffect(() => {
    if (!isCustomMode) return;
    
    const timer = setTimeout(() => {
      validateCode(customCode);
    }, 500);

    return () => clearTimeout(timer);
  }, [customCode, isCustomMode, validateCode]);

  const handleCustomCodeChange = (e) => {
    const newCode = e.target.value.toUpperCase();
    setCustomCode(newCode);
    onChange(newCode);
  };

  const toggleCustomMode = () => {
    if (isCustomMode) {
      // Switching back to auto mode
      setIsCustomMode(false);
      setCustomCode('');
      setValidationError(null);
      onChange(autoGeneratedCode);
    } else {
      // Switching to custom mode
      setIsCustomMode(true);
      setCustomCode(value || autoGeneratedCode);
    }
  };

  const displayError = externalError || validationError;

  return (
    <div className="space-y-2">
      <label className="block text-xs sm:text-sm font-medium text-gray-900 dark:text-gray-100 mb-1.5 sm:mb-2">
        Magic Code <span className="text-gray-500 text-xs">(Auto-generated)</span>
      </label>
      
      <div className="flex items-center gap-2">
        <div className="relative flex-1">
          <input
            type="text"
            value={isCustomMode ? customCode : (value || autoGeneratedCode)}
            onChange={isCustomMode ? handleCustomCodeChange : undefined}
            readOnly={!isCustomMode}
            disabled={disabled || isGenerating}
            placeholder="MAGIC-0001"
            className={`w-full px-3 sm:px-4 py-2 border-2 rounded-xl 
              ${displayError ? 'border-red-500' : isValid && value ? 'border-green-500' : 'border-gray-300 dark:border-gray-600'}
              ${!isCustomMode ? 'bg-gray-50 dark:bg-gray-800' : 'bg-white dark:bg-gray-700'}
              text-gray-900 dark:text-gray-100 
              focus:ring-2 focus:ring-magic-500 focus:border-magic-500 
              outline-none transition-all text-sm sm:text-base
              ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
          />
          
          {/* Status indicator */}
          <div className="absolute right-3 top-1/2 -translate-y-1/2">
            {isGenerating || isValidating ? (
              <Loader2 className="w-4 h-4 text-gray-400 animate-spin" />
            ) : isValid && value ? (
              <Check className="w-4 h-4 text-green-500" />
            ) : displayError ? (
              <X className="w-4 h-4 text-red-500" />
            ) : null}
          </div>
        </div>

        {/* Toggle custom mode button */}
        <button
          type="button"
          onClick={toggleCustomMode}
          disabled={disabled || isGenerating}
          className={`p-2 rounded-lg transition-colors ${
            isCustomMode 
              ? 'bg-magic-500 text-white hover:bg-magic-600' 
              : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
          } ${disabled ? 'opacity-50 cursor-not-allowed' : ''}`}
          title={isCustomMode ? 'Use auto-generated code' : 'Edit custom code'}
        >
          <Edit2 className="w-4 h-4" />
        </button>

        {/* Regenerate button (only in auto mode) */}
        {!isCustomMode && !startupId && (
          <button
            type="button"
            onClick={generateNewCode}
            disabled={disabled || isGenerating}
            className="p-2 rounded-lg bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300 
              hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors
              disabled:opacity-50 disabled:cursor-not-allowed"
            title="Generate new code"
          >
            <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          </button>
        )}
      </div>

      {/* Error message */}
      {displayError && (
        <p className="text-red-500 text-xs mt-1">{displayError}</p>
      )}

      {/* Helper text */}
      {isCustomMode && !displayError && (
        <p className="text-gray-500 text-xs">
          Enter a custom code in format MAGIC-XXXX (e.g., MAGIC-0042)
        </p>
      )}
    </div>
  );
}
